// flow-typed signature: 399aaa978c343d52f56d573d9f609474
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-for-of_v6.23.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-for-of'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-for-of' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-for-of/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-for-of/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-for-of/lib/index'>;
}
