// flow-typed signature: 2f7145898faab5dff4c1cbfaef28f462
// flow-typed version: <<STUB>>/date-arithmetic_v3.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-arithmetic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'date-arithmetic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'date-arithmetic/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'date-arithmetic/index' {
  declare module.exports: $Exports<'date-arithmetic'>;
}
declare module 'date-arithmetic/index.js' {
  declare module.exports: $Exports<'date-arithmetic'>;
}
declare module 'date-arithmetic/test.js' {
  declare module.exports: $Exports<'date-arithmetic/test'>;
}
