// flow-typed signature: e136c048ab06f84103f44a948c302b51
// flow-typed version: <<STUB>>/factorial-form_v0.0.8/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'factorial-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'factorial-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'factorial-form/__tests__/Field.spec' {
  declare module.exports: any;
}

declare module 'factorial-form/__tests__/Form.spec' {
  declare module.exports: any;
}

declare module 'factorial-form/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'factorial-form/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/babel-plugin-transform-decorators-legacy_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/babel-polyfill_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/babel-preset-stage-1_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/babel-register_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/eslint-config-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/eslint-plugin-node_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/eslint-plugin-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/flat_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/flow-copy-source_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/jest_v20.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/moment_v2.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/prettier-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/flow-typed/npm/rimraf_vx.x.x' {
  declare module.exports: any;
}

declare module 'factorial-form/lib/Field' {
  declare module.exports: any;
}

declare module 'factorial-form/lib/Form' {
  declare module.exports: any;
}

declare module 'factorial-form/lib/index' {
  declare module.exports: any;
}

declare module 'factorial-form/lib/numberParser' {
  declare module.exports: any;
}

declare module 'factorial-form/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'factorial-form/__tests__/Field.spec.js' {
  declare module.exports: $Exports<'factorial-form/__tests__/Field.spec'>;
}
declare module 'factorial-form/__tests__/Form.spec.js' {
  declare module.exports: $Exports<'factorial-form/__tests__/Form.spec'>;
}
declare module 'factorial-form/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'factorial-form/coverage/lcov-report/prettify'>;
}
declare module 'factorial-form/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'factorial-form/coverage/lcov-report/sorter'>;
}
declare module 'factorial-form/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/babel-plugin-transform-decorators-legacy_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/babel-plugin-transform-decorators-legacy_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/babel-polyfill_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/babel-polyfill_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/babel-preset-stage-1_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/babel-preset-stage-1_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/babel-register_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/babel-register_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/eslint-config-standard_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/eslint-config-standard_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/eslint-plugin-node_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/eslint-plugin-node_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/eslint-plugin-promise_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/eslint-plugin-standard_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/eslint-plugin-standard_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/flat_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/flat_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/flow-copy-source_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/flow-copy-source_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/husky_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/jest_v20.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/jest_v20.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/moment_v2.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/moment_v2.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/prettier-standard_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/prettier-standard_vx.x.x'>;
}
declare module 'factorial-form/flow-typed/npm/rimraf_vx.x.x.js' {
  declare module.exports: $Exports<'factorial-form/flow-typed/npm/rimraf_vx.x.x'>;
}
declare module 'factorial-form/lib/Field.js' {
  declare module.exports: $Exports<'factorial-form/lib/Field'>;
}
declare module 'factorial-form/lib/Form.js' {
  declare module.exports: $Exports<'factorial-form/lib/Form'>;
}
declare module 'factorial-form/lib/index.js' {
  declare module.exports: $Exports<'factorial-form/lib/index'>;
}
declare module 'factorial-form/lib/numberParser.js' {
  declare module.exports: $Exports<'factorial-form/lib/numberParser'>;
}
declare module 'factorial-form/lib/types.js' {
  declare module.exports: $Exports<'factorial-form/lib/types'>;
}
