// flow-typed signature: 80f8ec9af4cd200683497974f104bb78
// flow-typed version: <<STUB>>/html-webpack-inline-chunk-plugin_v1.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-inline-chunk-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-inline-chunk-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'html-webpack-inline-chunk-plugin/index' {
  declare module.exports: $Exports<'html-webpack-inline-chunk-plugin'>;
}
declare module 'html-webpack-inline-chunk-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-inline-chunk-plugin'>;
}
