// flow-typed signature: 50a9e9376d63ab5fa8081309ee88ee2e
// flow-typed version: <<STUB>>/mobx-rest-jquery-adapter_v1.0.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-rest-jquery-adapter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-rest-jquery-adapter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-rest-jquery-adapter/__tests__/adapter.spec' {
  declare module.exports: any;
}

declare module 'mobx-rest-jquery-adapter/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-rest-jquery-adapter/__tests__/adapter.spec.js' {
  declare module.exports: $Exports<'mobx-rest-jquery-adapter/__tests__/adapter.spec'>;
}
declare module 'mobx-rest-jquery-adapter/lib/index.js' {
  declare module.exports: $Exports<'mobx-rest-jquery-adapter/lib/index'>;
}
