// flow-typed signature: 8afe249e556c96e6d10d8826ade0cc20
// flow-typed version: <<STUB>>/mobx-rest_v2.1.7/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-rest/__tests__/Collection.spec' {
  declare module.exports: any;
}

declare module 'mobx-rest/__tests__/mocks/api' {
  declare module.exports: any;
}

declare module 'mobx-rest/__tests__/Model.spec' {
  declare module.exports: any;
}

declare module 'mobx-rest/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'mobx-rest/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/babel-plugin-transform-decorators-legacy_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/babel-polyfill_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/babel-preset-stage-1_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/babel-register_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/eslint-config-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/eslint-plugin-node_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/eslint-plugin-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/jest_v19.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/flow-typed/npm/prettier-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'mobx-rest/lib/apiClient' {
  declare module.exports: any;
}

declare module 'mobx-rest/lib/Collection' {
  declare module.exports: any;
}

declare module 'mobx-rest/lib/ErrorObject' {
  declare module.exports: any;
}

declare module 'mobx-rest/lib/index' {
  declare module.exports: any;
}

declare module 'mobx-rest/lib/Model' {
  declare module.exports: any;
}

declare module 'mobx-rest/lib/Request' {
  declare module.exports: any;
}

declare module 'mobx-rest/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-rest/__tests__/Collection.spec.js' {
  declare module.exports: $Exports<'mobx-rest/__tests__/Collection.spec'>;
}
declare module 'mobx-rest/__tests__/mocks/api.js' {
  declare module.exports: $Exports<'mobx-rest/__tests__/mocks/api'>;
}
declare module 'mobx-rest/__tests__/Model.spec.js' {
  declare module.exports: $Exports<'mobx-rest/__tests__/Model.spec'>;
}
declare module 'mobx-rest/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'mobx-rest/coverage/lcov-report/prettify'>;
}
declare module 'mobx-rest/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'mobx-rest/coverage/lcov-report/sorter'>;
}
declare module 'mobx-rest/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/babel-plugin-transform-decorators-legacy_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/babel-plugin-transform-decorators-legacy_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/babel-polyfill_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/babel-polyfill_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/babel-preset-stage-1_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/babel-preset-stage-1_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/babel-register_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/babel-register_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/eslint-config-standard_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/eslint-config-standard_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/eslint-plugin-node_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/eslint-plugin-node_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/eslint-plugin-promise_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/eslint-plugin-standard_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/eslint-plugin-standard_vx.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/jest_v19.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/jest_v19.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'mobx-rest/flow-typed/npm/prettier-standard_vx.x.x.js' {
  declare module.exports: $Exports<'mobx-rest/flow-typed/npm/prettier-standard_vx.x.x'>;
}
declare module 'mobx-rest/lib/apiClient.js' {
  declare module.exports: $Exports<'mobx-rest/lib/apiClient'>;
}
declare module 'mobx-rest/lib/Collection.js' {
  declare module.exports: $Exports<'mobx-rest/lib/Collection'>;
}
declare module 'mobx-rest/lib/ErrorObject.js' {
  declare module.exports: $Exports<'mobx-rest/lib/ErrorObject'>;
}
declare module 'mobx-rest/lib/index.js' {
  declare module.exports: $Exports<'mobx-rest/lib/index'>;
}
declare module 'mobx-rest/lib/Model.js' {
  declare module.exports: $Exports<'mobx-rest/lib/Model'>;
}
declare module 'mobx-rest/lib/Request.js' {
  declare module.exports: $Exports<'mobx-rest/lib/Request'>;
}
declare module 'mobx-rest/lib/types.js' {
  declare module.exports: $Exports<'mobx-rest/lib/types'>;
}
