// flow-typed signature: ab578773b05be1733166a9dffbe4cff4
// flow-typed version: <<STUB>>/plurals-cldr_v1.0.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plurals-cldr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plurals-cldr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plurals-cldr/dist/plurals-cldr' {
  declare module.exports: any;
}

declare module 'plurals-cldr/dist/plurals-cldr.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plurals-cldr/dist/plurals-cldr.js' {
  declare module.exports: $Exports<'plurals-cldr/dist/plurals-cldr'>;
}
declare module 'plurals-cldr/dist/plurals-cldr.min.js' {
  declare module.exports: $Exports<'plurals-cldr/dist/plurals-cldr.min'>;
}
declare module 'plurals-cldr/index' {
  declare module.exports: $Exports<'plurals-cldr'>;
}
declare module 'plurals-cldr/index.js' {
  declare module.exports: $Exports<'plurals-cldr'>;
}
