// flow-typed signature: b065ac2a8102bce20b52116830930ecb
// flow-typed version: <<STUB>>/react-prop-types_v0.4.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-prop-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-prop-types/lib/all' {
  declare module.exports: any;
}

declare module 'react-prop-types/lib/componentOrElement' {
  declare module.exports: any;
}

declare module 'react-prop-types/lib/deprecated' {
  declare module.exports: any;
}

declare module 'react-prop-types/lib/elementType' {
  declare module.exports: any;
}

declare module 'react-prop-types/lib/index' {
  declare module.exports: any;
}

declare module 'react-prop-types/lib/isRequiredForA11y' {
  declare module.exports: any;
}

declare module 'react-prop-types/lib/utils/createChainableTypeChecker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-prop-types/lib/all.js' {
  declare module.exports: $Exports<'react-prop-types/lib/all'>;
}
declare module 'react-prop-types/lib/componentOrElement.js' {
  declare module.exports: $Exports<'react-prop-types/lib/componentOrElement'>;
}
declare module 'react-prop-types/lib/deprecated.js' {
  declare module.exports: $Exports<'react-prop-types/lib/deprecated'>;
}
declare module 'react-prop-types/lib/elementType.js' {
  declare module.exports: $Exports<'react-prop-types/lib/elementType'>;
}
declare module 'react-prop-types/lib/index.js' {
  declare module.exports: $Exports<'react-prop-types/lib/index'>;
}
declare module 'react-prop-types/lib/isRequiredForA11y.js' {
  declare module.exports: $Exports<'react-prop-types/lib/isRequiredForA11y'>;
}
declare module 'react-prop-types/lib/utils/createChainableTypeChecker.js' {
  declare module.exports: $Exports<'react-prop-types/lib/utils/createChainableTypeChecker'>;
}
