// flow-typed signature: 537c778e758e16f04b685036e7d3e1cd
// flow-typed version: <<STUB>>/resolve-pathname_v2.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resolve-pathname'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resolve-pathname' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resolve-pathname/es/index' {
  declare module.exports: any;
}

declare module 'resolve-pathname/umd/resolve-pathname' {
  declare module.exports: any;
}

declare module 'resolve-pathname/umd/resolve-pathname.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resolve-pathname/es/index.js' {
  declare module.exports: $Exports<'resolve-pathname/es/index'>;
}
declare module 'resolve-pathname/index' {
  declare module.exports: $Exports<'resolve-pathname'>;
}
declare module 'resolve-pathname/index.js' {
  declare module.exports: $Exports<'resolve-pathname'>;
}
declare module 'resolve-pathname/umd/resolve-pathname.js' {
  declare module.exports: $Exports<'resolve-pathname/umd/resolve-pathname'>;
}
declare module 'resolve-pathname/umd/resolve-pathname.min.js' {
  declare module.exports: $Exports<'resolve-pathname/umd/resolve-pathname.min'>;
}
