// flow-typed signature: 46202054a8c889a00fe5689e1fa87ee0
// flow-typed version: <<STUB>>/scroll-into-view_v1.8.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scroll-into-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scroll-into-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scroll-into-view/example/index.browser' {
  declare module.exports: any;
}

declare module 'scroll-into-view/example/index' {
  declare module.exports: any;
}

declare module 'scroll-into-view/scrollIntoView' {
  declare module.exports: any;
}

declare module 'scroll-into-view/test/test.browser' {
  declare module.exports: any;
}

declare module 'scroll-into-view/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scroll-into-view/example/index.browser.js' {
  declare module.exports: $Exports<'scroll-into-view/example/index.browser'>;
}
declare module 'scroll-into-view/example/index.js' {
  declare module.exports: $Exports<'scroll-into-view/example/index'>;
}
declare module 'scroll-into-view/scrollIntoView.js' {
  declare module.exports: $Exports<'scroll-into-view/scrollIntoView'>;
}
declare module 'scroll-into-view/test/test.browser.js' {
  declare module.exports: $Exports<'scroll-into-view/test/test.browser'>;
}
declare module 'scroll-into-view/test/test.js' {
  declare module.exports: $Exports<'scroll-into-view/test/test'>;
}
