// flow-typed signature: 56594f9144bb5eafbff1e5ecfbb0b911
// flow-typed version: <<STUB>>/svg4everybody_v2.1.8/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg4everybody'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg4everybody' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg4everybody/dist/svg4everybody' {
  declare module.exports: any;
}

declare module 'svg4everybody/dist/svg4everybody.legacy' {
  declare module.exports: any;
}

declare module 'svg4everybody/dist/svg4everybody.legacy.min' {
  declare module.exports: any;
}

declare module 'svg4everybody/dist/svg4everybody.min' {
  declare module.exports: any;
}

declare module 'svg4everybody/Gruntfile' {
  declare module.exports: any;
}

declare module 'svg4everybody/lib/svg4everybody' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg4everybody/dist/svg4everybody.js' {
  declare module.exports: $Exports<'svg4everybody/dist/svg4everybody'>;
}
declare module 'svg4everybody/dist/svg4everybody.legacy.js' {
  declare module.exports: $Exports<'svg4everybody/dist/svg4everybody.legacy'>;
}
declare module 'svg4everybody/dist/svg4everybody.legacy.min.js' {
  declare module.exports: $Exports<'svg4everybody/dist/svg4everybody.legacy.min'>;
}
declare module 'svg4everybody/dist/svg4everybody.min.js' {
  declare module.exports: $Exports<'svg4everybody/dist/svg4everybody.min'>;
}
declare module 'svg4everybody/Gruntfile.js' {
  declare module.exports: $Exports<'svg4everybody/Gruntfile'>;
}
declare module 'svg4everybody/lib/svg4everybody.js' {
  declare module.exports: $Exports<'svg4everybody/lib/svg4everybody'>;
}
