// flow-typed signature: 37fee1eb67f82ea10a5ba23eac081f5d
// flow-typed version: <<STUB>>/tcomb-react_v0.9.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tcomb-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tcomb-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tcomb-react/lib/parse' {
  declare module.exports: any;
}

declare module 'tcomb-react/lib/toMarkdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tcomb-react/index' {
  declare module.exports: $Exports<'tcomb-react'>;
}
declare module 'tcomb-react/index.js' {
  declare module.exports: $Exports<'tcomb-react'>;
}
declare module 'tcomb-react/lib/parse.js' {
  declare module.exports: $Exports<'tcomb-react/lib/parse'>;
}
declare module 'tcomb-react/lib/toMarkdown.js' {
  declare module.exports: $Exports<'tcomb-react/lib/toMarkdown'>;
}
