// flow-typed signature: ca57290ca9a0576bfa2021a4a9e0d090
// flow-typed version: <<STUB>>/uncontrollable_v3.3.1 || 4.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uncontrollable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uncontrollable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uncontrollable/batching' {
  declare module.exports: any;
}

declare module 'uncontrollable/createUncontrollable' {
  declare module.exports: any;
}

declare module 'uncontrollable/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uncontrollable/batching.js' {
  declare module.exports: $Exports<'uncontrollable/batching'>;
}
declare module 'uncontrollable/createUncontrollable.js' {
  declare module.exports: $Exports<'uncontrollable/createUncontrollable'>;
}
declare module 'uncontrollable/index' {
  declare module.exports: $Exports<'uncontrollable'>;
}
declare module 'uncontrollable/index.js' {
  declare module.exports: $Exports<'uncontrollable'>;
}
declare module 'uncontrollable/utils.js' {
  declare module.exports: $Exports<'uncontrollable/utils'>;
}
