// flow-typed signature: 168451f832a59fb111115323171b34cb
// flow-typed version: <<STUB>>/wtfis_v1.0.5/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wtfis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wtfis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wtfis/array' {
  declare module.exports: any;
}

declare module 'wtfis/false' {
  declare module.exports: any;
}

declare module 'wtfis/isNullOrUndefined' {
  declare module.exports: any;
}

declare module 'wtfis/null' {
  declare module.exports: any;
}

declare module 'wtfis/number' {
  declare module.exports: any;
}

declare module 'wtfis/object' {
  declare module.exports: any;
}

declare module 'wtfis/string' {
  declare module.exports: any;
}

declare module 'wtfis/true' {
  declare module.exports: any;
}

declare module 'wtfis/undefined' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wtfis/array.js' {
  declare module.exports: $Exports<'wtfis/array'>;
}
declare module 'wtfis/false.js' {
  declare module.exports: $Exports<'wtfis/false'>;
}
declare module 'wtfis/isNullOrUndefined.js' {
  declare module.exports: $Exports<'wtfis/isNullOrUndefined'>;
}
declare module 'wtfis/null.js' {
  declare module.exports: $Exports<'wtfis/null'>;
}
declare module 'wtfis/number.js' {
  declare module.exports: $Exports<'wtfis/number'>;
}
declare module 'wtfis/object.js' {
  declare module.exports: $Exports<'wtfis/object'>;
}
declare module 'wtfis/string.js' {
  declare module.exports: $Exports<'wtfis/string'>;
}
declare module 'wtfis/true.js' {
  declare module.exports: $Exports<'wtfis/true'>;
}
declare module 'wtfis/undefined.js' {
  declare module.exports: $Exports<'wtfis/undefined'>;
}
